name:                tagredactorv2
version:             0.1.0.0
github:              "AleksPilot/mp3-tagRedactor"
license:             BSD3
author:              Aleksandr Tarasov
maintainer:          a.tarasov7@g.nsu.ru
copyright:           2021 Aleksandr Tarasov

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at https://github.com/AleksPilot/mp3-tagRedactor

dependencies:
- base >= 4.7 && < 5
- bytestring

library:
  source-dirs: src

executables:
  tagredactorv2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tagredactorv2

tests:
  tagredactorv2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tagredactorv2
